.TH mystrlen 3 "September 2026" "Version 1.0" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B int mystrlen(const char *s);
.SH DESCRIPTION
The \fBmystrlen\fR function calculates the length of the string pointed to by \fBs\fR, excluding the terminating null byte. It returns 0 if the input string is NULL.
.SH AUTHOR
Written by Abdur Rehman
