client: main.o myfilefunctions.o mystrfunctions.o
	gcc main.o myfilefunctions.o mystrfunctions.o -o ../bin/client
myfilefunctions.o: myfilefunctions.c 
	gcc -c myfilefunctions.c
mystrfunctions.o: mystrfunctions.c 
	gcc -c mystrfunctions.c
